#!/usr/bin/env bash
# Concatenates supabase/migrations/*.sql into one file that can be pasted into the Supabase
# SQL Editor (Dashboard → SQL Editor → New query → paste → Run). It also records each migration
# in supabase_migrations.schema_migrations, so a later `supabase db push` knows they are applied.
#
# Usage: scripts/bundle-migrations.sh [out-file] [since-version]
#   since-version: include only migrations with a version >= this (for an upgrade file).
set -euo pipefail
out="${1:-supabase/dist/all-migrations.sql}"
since="${2:-0}"
mkdir -p "$(dirname "$out")"
{
  echo "-- Generated by scripts/bundle-migrations.sh — do not edit. Runs as a single transaction."
  echo "begin;"
  echo "create schema if not exists supabase_migrations;"
  echo "create table if not exists supabase_migrations.schema_migrations (version text primary key, statements text[], name text);"
  for f in supabase/migrations/*.sql; do
    base="$(basename "$f" .sql)"
    version="${base%%_*}"
    name="${base#*_}"
    [[ "$version" < "$since" ]] && continue
    echo
    echo "-- ======================================================================"
    echo "-- $base"
    echo "-- ======================================================================"
    cat "$f"
    echo
    echo "insert into supabase_migrations.schema_migrations (version, name) values ('$version', '$name') on conflict (version) do nothing;"
  done
  echo "commit;"
} > "$out"
echo "wrote $out"
